// Dados mockados para desenvolvimento da UI.
// Todos os tipos vêm de src/types/student.ts (view types com joins resolvidos).
// Serão substituídos por queries Supabase na integração final.

import type {
  CohortWithProgress,
  CourseWithProgress,
  ModuleWithProgress,
  LiveSessionWithCohort,
  CertificateView,
  ForumCategoryWithCount,
  ForumThreadWithMeta,
  ForumReplyWithMeta,
  CommentWithAuthor,
} from '@/types/student'

export const MOCK_COHORTS: CohortWithProgress[] = [
  {
    id: '1',
    name: 'Mentoria — Turma Maio 2026',
    slug: 'mentoria-maio-2026',
    has_live_sessions: true,
    expires_at: '2026-11-30T03:00:00.000Z',
    status: 'ACTIVE',
    auto_renew_enabled: false,
    progressPercent: 34,
    lastAccessedLessonTitle: 'Frameworks de decisão com IA',
    lastAccessedLessonSlug: 'frameworks-decisao-ia',
    lastAccessedCourseSlug: 'estrategia-ia',
    nextLiveSessionAt: '2026-05-08T22:00:00.000Z',
  },
  {
    id: '2',
    name: 'Curso Online — Padrão',
    slug: 'online-padrao',
    has_live_sessions: false,
    expires_at: '2026-06-15T03:00:00.000Z',
    status: 'ACTIVE',
    auto_renew_enabled: false,
    progressPercent: 72,
    lastAccessedLessonTitle: 'Claude Code na prática',
    lastAccessedLessonSlug: 'claude-code-pratica',
    lastAccessedCourseSlug: 'claude-code',
    nextLiveSessionAt: null,
  },
]

export const MOCK_COURSES: CourseWithProgress[] = [
  {
    id: 'c1',
    slug: 'estrategia-ia',
    title: 'Estratégia com IA',
    description: 'Frameworks de decisão, planejamento e execução com modelos de linguagem.',
    cover_image_url: null,
    progressPercent: 34,
    totalLessons: 24,
    completedLessons: 8,
    cohortName: 'Mentoria — Turma Maio 2026',
    cohortSlug: 'mentoria-maio-2026',
    isPartialAccess: false,
    accessibleModulesCount: 4,
    totalModulesCount: 4,
  },
  {
    id: 'c2',
    slug: 'claude-code',
    title: 'Claude Code',
    description: 'Do zero ao fluxo de trabalho com Claude Code, Cursor e agentes de código.',
    cover_image_url: null,
    progressPercent: 72,
    totalLessons: 18,
    completedLessons: 13,
    cohortName: 'Curso Online — Padrão',
    cohortSlug: 'online-padrao',
    isPartialAccess: false,
    accessibleModulesCount: 3,
    totalModulesCount: 3,
  },
  {
    id: 'c3',
    slug: 'multi-agent',
    title: 'Multi-Agent Systems',
    description: 'Arquitetura e orquestração de sistemas com múltiplos agentes.',
    cover_image_url: null,
    progressPercent: 0,
    totalLessons: 16,
    completedLessons: 0,
    cohortName: 'Mentoria — Turma Maio 2026',
    cohortSlug: 'mentoria-maio-2026',
    isPartialAccess: true,
    accessibleModulesCount: 1,
    totalModulesCount: 4,
  },
]

export const MOCK_MODULES: ModuleWithProgress[] = [
  {
    id: 'm1',
    slug: 'fundamentos',
    title: 'Fundamentos',
    sortOrder: 1,
    isLocked: false,
    lockedByCohortName: null,
    lockedByCohortSlug: null,
    totalLessons: 6,
    completedLessons: 6,
  },
  {
    id: 'm2',
    slug: 'prompt-engineering',
    title: 'Prompt Engineering Avançado',
    sortOrder: 2,
    isLocked: false,
    lockedByCohortName: null,
    lockedByCohortSlug: null,
    totalLessons: 8,
    completedLessons: 5,
  },
  {
    id: 'm3',
    slug: 'agentes-autonomos',
    title: 'Agentes Autônomos',
    sortOrder: 3,
    isLocked: false,
    lockedByCohortName: null,
    lockedByCohortSlug: null,
    totalLessons: 7,
    completedLessons: 2,
  },
  {
    id: 'm4',
    slug: 'producao-e-deploy',
    title: 'Produção & Deploy',
    sortOrder: 4,
    isLocked: true,
    lockedByCohortName: 'Mentoria — Turma Avançada',
    lockedByCohortSlug: 'mentoria-avancada',
    totalLessons: 5,
    completedLessons: 0,
  },
]

export const MOCK_CERTIFICATES: CertificateView[] = [
  {
    id: 'cert1',
    verification_code: 'AIOX-2026-X7K9P2',
    issued_at: '2026-04-20T03:00:00.000Z',
    pdf_storage_path: 'certificates/cert1.pdf',
    courseName: 'Claude Code',
    courseSlug: 'claude-code',
    cohortName: 'Curso Online — Padrão',
  },
]

export const MOCK_FORUM_CATEGORIES: ForumCategoryWithCount[] = [
  {
    id: 'cat1',
    slug: 'duvidas-tecnicas',
    name: 'Dúvidas Técnicas',
    description: 'Perguntas sobre implementação, código e ferramentas.',
    color: '#FF3A0E',
    sort_order: 1,
    is_active: true,
    threadCount: 14,
  },
  {
    id: 'cat2',
    slug: 'geral',
    name: 'Geral',
    description: 'Discussões livres sobre IA, carreira e projetos.',
    color: '#22C55E',
    sort_order: 2,
    is_active: true,
    threadCount: 8,
  },
  {
    id: 'cat3',
    slug: 'networking',
    name: 'Networking',
    description: 'Apresentações, colaborações e oportunidades.',
    color: '#A78BFA',
    sort_order: 3,
    is_active: true,
    threadCount: 5,
  },
]

export const MOCK_FORUM_THREADS: ForumThreadWithMeta[] = [
  {
    id: 't1',
    slug: 'como-estruturar-system-prompt-para-agentes',
    title: 'Como estruturar system prompt para agentes com múltiplos papéis?',
    content: 'Estou tentando criar um agente que alterna entre pesquisador e redator. Qual a melhor abordagem para o system prompt?\n\nJá tentei usar XML tags mas o modelo ignora às vezes.',
    authorName: 'Ana Beatriz',
    authorRole: 'STUDENT',
    categorySlug: 'duvidas-tecnicas',
    categoryName: 'Dúvidas Técnicas',
    created_at: '2026-05-03T17:30:00.000Z',
    last_activity_at: '2026-05-04T12:15:00.000Z',
    replyCount: 3,
    voteCount: 7,
    is_resolved: true,
    is_pinned: false,
    view_count: 42,
  },
  {
    id: 't2',
    slug: 'dica-de-carreira-transicao-para-ia',
    title: 'Dica de carreira: como fiz a transição para trabalhar com IA',
    content: 'Depois de 10 anos como dev backend, decidi migrar para engenharia de prompts e automação com IA. Quero compartilhar o que funcionou.',
    authorName: 'Carlos Henrique',
    authorRole: 'STUDENT',
    categorySlug: 'geral',
    categoryName: 'Geral',
    created_at: '2026-05-01T13:00:00.000Z',
    last_activity_at: '2026-05-01T21:20:00.000Z',
    replyCount: 12,
    voteCount: 24,
    is_resolved: false,
    is_pinned: true,
    view_count: 118,
  },
  {
    id: 't3',
    slug: 'erro-ao-usar-tool-use-com-claude-api',
    title: 'Erro 400 ao usar tool_use com a API do Claude — alguém já viu isso?',
    content: 'Estou recebendo `{"type":"error","error":{"type":"invalid_request_error"}}` ao passar tools com input_schema aninhado.',
    authorName: 'Fernanda Lima',
    authorRole: 'STUDENT',
    categorySlug: 'duvidas-tecnicas',
    categoryName: 'Dúvidas Técnicas',
    created_at: '2026-05-04T23:00:00.000Z',
    last_activity_at: '2026-05-05T11:00:00.000Z',
    replyCount: 1,
    voteCount: 3,
    is_resolved: false,
    is_pinned: false,
    view_count: 15,
  },
]

export const MOCK_FORUM_REPLIES: ForumReplyWithMeta[] = [
  {
    id: 'r1',
    thread_id: 't1',
    authorName: 'João Guirunas',
    authorRole: 'MENTOR',
    content: 'Ótima pergunta! Para agentes multi-papel, prefiro usar uma seção `<role>` explícita no início do prompt e um `<current_role>` dinâmico que você injeta a cada turno. O XML funciona bem quando você usa `prefill` no assistant turn para forçar o modelo a iniciar dentro da tag.',
    created_at: '2026-05-03T18:00:00.000Z',
    voteCount: 5,
    is_accepted_answer: true,
    parent_reply_id: null,
    deleted_at: null,
  },
  {
    id: 'r2',
    thread_id: 't1',
    authorName: 'Ricardo Souza',
    authorRole: 'STUDENT',
    content: 'Confirmo o que o João disse. Eu também uso um `<mode>` tag e funciona muito bem.',
    created_at: '2026-05-03T19:30:00.000Z',
    voteCount: 2,
    is_accepted_answer: false,
    parent_reply_id: null,
    deleted_at: null,
  },
  {
    id: 'r3',
    thread_id: 't1',
    authorName: 'Ana Beatriz',
    authorRole: 'STUDENT',
    content: 'Perfeito, resolveu! O prefill foi a chave. Obrigada!',
    created_at: '2026-05-04T12:15:00.000Z',
    voteCount: 1,
    is_accepted_answer: false,
    parent_reply_id: 'r1',
    deleted_at: null,
  },
]

export const MOCK_LIVE_SESSIONS: LiveSessionWithCohort[] = [
  {
    id: 'ls1',
    title: 'Aula ao Vivo — Frameworks de Decisão com IA',
    description: 'Vamos explorar como estruturar processos de decisão assistidos por modelos de linguagem, com exercícios práticos.',
    scheduled_at: '2026-05-08T22:00:00.000Z',
    duration_minutes: 90,
    cohortName: 'Mentoria — Turma Maio 2026',
    cohortSlug: 'mentoria-maio-2026',
    meeting_url: null,
    recording_url: null,
  },
  {
    id: 'ls2',
    title: 'Sessão de Dúvidas — Multi-Agent Systems',
    description: 'Tire suas dúvidas sobre a implementação de sistemas multi-agente.',
    scheduled_at: '2026-05-15T22:00:00.000Z',
    duration_minutes: 60,
    cohortName: 'Mentoria — Turma Maio 2026',
    cohortSlug: 'mentoria-maio-2026',
    meeting_url: null,
    recording_url: null,
  },
  {
    id: 'ls3',
    title: 'Workshop — Claude Code na Prática',
    description: 'Hands-on: configurando Claude Code, criando skills customizadas e automatizando fluxos de desenvolvimento.',
    scheduled_at: '2026-04-24T22:00:00.000Z',
    duration_minutes: 120,
    cohortName: 'Mentoria — Turma Maio 2026',
    cohortSlug: 'mentoria-maio-2026',
    meeting_url: null,
    recording_url: 'https://vimeo.com/123456789',
  },
]

export const MOCK_COMMENTS: CommentWithAuthor[] = [
  {
    id: 'c1',
    lesson_id: 'lesson-demo',
    authorId: 'uuid-mentor-1',
    authorName: 'João Guirunas',
    authorRole: 'MENTOR',
    content: 'Ótima aula! Lembrem de que os conceitos desta aula serão fundamentais para o módulo de agentes.',
    created_at: '2026-05-01T13:00:00.000Z',
    updated_at: '2026-05-01T13:00:00.000Z',
    deleted_at: null,
    is_pinned: true,
    parent_comment_id: null,
  },
  {
    id: 'c2',
    lesson_id: 'lesson-demo',
    authorId: 'uuid-student-1',
    authorName: 'Ana Beatriz',
    authorRole: 'STUDENT',
    content: 'Ficou muito claro! Tenho uma dúvida: a técnica de prefill funciona também com Sonnet ou apenas com Opus?',
    created_at: '2026-05-02T17:30:00.000Z',
    updated_at: '2026-05-02T17:30:00.000Z',
    deleted_at: null,
    is_pinned: false,
    parent_comment_id: null,
  },
  {
    id: 'c3',
    lesson_id: 'lesson-demo',
    authorId: 'uuid-mentor-1',
    authorName: 'João Guirunas',
    authorRole: 'MENTOR',
    content: 'Funciona em todos os modelos da família Claude! O prefill é um recurso da API, não do modelo específico.',
    created_at: '2026-05-02T18:00:00.000Z',
    updated_at: '2026-05-02T18:00:00.000Z',
    deleted_at: null,
    is_pinned: false,
    parent_comment_id: 'c2',
  },
  {
    id: 'c4',
    lesson_id: 'lesson-demo',
    authorId: 'uuid-student-2',
    authorName: 'Carlos Henrique',
    authorRole: 'STUDENT',
    content: '',
    created_at: '2026-05-03T12:00:00.000Z',
    updated_at: '2026-05-03T12:00:00.000Z',
    deleted_at: '2026-05-03T13:00:00.000Z',
    is_pinned: false,
    parent_comment_id: null,
  },
]
